steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/store-microservices-430116/store-registry/products-ms-prod",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/store-microservices-430116/store-registry/products-ms-prod",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
